FiShare/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from users import views as users_view
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', users_view.register, name='register'),
    path('profile/', users_view.profile, name='profile'),
    path('', include('allusers.urls')),
    path('', include('root.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allusers/urls.py
from django.urls import path,include
from users import views as users_view
from django.conf.urls.static import static
from django.conf import settings
from root.views import MyFileFolderView


urlpatterns = [
    path('all_users/', users_view.user_list, name='all_users'),
    path('all_users/<int:user_id>', MyFileFolderView.as_view(template_name='root/home_base.html'),name='user_repo'),
    path('all_users/', include('root.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/urls.py
from django.urls import path
from .views import (PostCreateView,download_file,FileDelete,create_folder,
                    MyFileFolderView,home,download_folder,FolderDelete, 
                    toggle_favorite, FolderUpload, FolderUploadIndex)
from django.conf.urls.static import static
from django.conf import settings


urlpatterns =[
    path('',home ,name='home'),
    path('my_files/',MyFileFolderView.as_view(),name='all_files'),
    path('my_files/new/',PostCreateView.as_view(template_name='root/add_file.html'),name='all_files_create'),
    path('my_files/<int:pk>/delete/', FileDelete.as_view(), name='delete_file'),
    path('my_files/folder/create', create_folder,name='create_folder'),
    path('my_files/folder/create/<int:parent_folder_id>/',PostCreateView.as_view(template_name='root/add_file.html'),name='create_file_in_folder'),
    path('my_files/folder/create/folder/<int:parent_folder_id>/',create_folder,name='create_folder_in_folder'),
    path('my_files/<int:parent_folder_id>/',MyFileFolderView.as_view(template_name='root/subfolder.html'),name='subfolder'),
    path('download/file/<str:file_path>/', download_file, name='download_file'),
    path('download/folder/<int:pk>/', download_folder, name='download_folder'),
    path('delete/folder/<int:pk>/', FolderDelete.as_view(), name='delete_folder'),
    path('toggle_favorite/<str:model>/<int:pk>/', toggle_favorite , name='toggle_favorite'),
    path('folder_upload/<int:pk>/', FolderUpload, name='folder_upload'),
    path('folder_upload_index/', FolderUploadIndex, name='folder-upload-index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allusers/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user =models.OneToOneField(User, on_delete=models.CASCADE)
    image= models.ImageField(default='default.jpeg',upload_to='profile_pics')
    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        img=Image.open(self.image.path)

        if img.height>300 or img.width>300:
            output_size=(300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegistrationForm(UserCreationForm):
	email=forms.EmailField()

	class Meta:
		model=User
		fields=['username', 'email' ,'password1','password2']
		
class UserUpdateForm(forms.ModelForm):
	email=forms.EmailField()
	class Meta:
		model=User
		fields=['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model=Profile
		fields=['image']

allusers/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegistrationForm,UserUpdateForm,ProfileUpdateForm
from django.contrib.auth.models import User

# Create your views here.
def register(request):
	if request.method=='POST':
		form=UserRegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			username=form.cleaned_data.get('username')
			messages.success(request, f'Account Created for {username}!')
			return redirect('login')	
	else:
		form=UserRegistrationForm()
	return render(request,'users/register.html',{'form':form})

@login_required
def profile(request):
	if request.method == 'POST':
		u_update = UserUpdateForm(request.POST, instance=request.user)
		p_update = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
		
		if u_update.is_valid():
			u_update.save()
			messages.success(request, 'Account Updated!')
			return redirect('profile')
		
		if p_update.is_valid():
			p_update.save()
			messages.success(request, 'Account Updated!')
			return redirect('profile')
	else:
		u_update = UserUpdateForm(instance=request.user)
		p_update = ProfileUpdateForm(instance=request.user.profile)
	
	update_form = {
		'u_update': u_update,
		'p_update': p_update
	}
	
	return render(request, 'users/profile.html', update_form)


def user_list(request):
    users = User.objects.all()
    return render(request, 'users/all_users.html', {'users': users})

users/templates/users/all_users.html
{% extends "root/base.html" %} 
{% block content %}
<div class="user-card-container">
  {% for user in users %}
  <div class="card" style="margin: 0%; margin-bottom: 5%; ">
    <div class="card-body">
      <div class="media">
        <img class="account-img" src="{{user.profile.image.url}}">
        <div class="media-body">
          <h2 class="account-heading"> <a href="{%url 'user_repo' user.id%}"> {{user.username}} </a></h2>
          <p class="text-secondary">{{user.email}}</p>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

users/templates/users/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'root/main.css' %}">

    {% if title %}
        <title>FiShare - {{ title }}</title>
    {% else %}
        <title>FiShare</title>
    {% endif %}
</head>
<body class="bg">
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid" >
          <a class="navbar-brand" href="#">
            <img src="{% static 'root/logo.png' %}" alt="Bootstrap" width="30" height="30" >
            FiShare
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <!-- <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="#">Home</a>
            </div> -->
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            	{% if user.is_authenticated %}
            	 <a class="" href="{% url 'logout'%}">Logout</a>
            	 <a class="" href="{% url 'profile'%}">Profile</a>
            	{%else%} 
	              <a class="" href="{% url 'register'%}">Register</a>
	            {%endif%}  
            </div>
          </div>
        </div>
      </nav>
    </div>
    </header>




    <main role="main" class="container">
      <div class="row">
        <div class="col">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          <div class="center-screen">
            <div class="content-section" >
            <form method="POST">
                  {% csrf_token %}
                  <fieldset class="form-group">
                      <legend class="border-bottom mb-4">Log In</legend>
                      {{ form|crispy }}
                  </fieldset>
                  <div class="form-group">
                      <button class="btn btn-outline-info" type="submit">Log In</button>
                  </div>
              </form>
              <div class="border-top pt-3">
                  <small class="text-muted">
                    Need An Account? <a class="ml-2" href= "{% url 'register'%}" >Sign Up</a>
                  </small>
                </div>   
            </div>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/logout.html
{% extends "root/base.html" %} {% block content %}
<div class="content-section">
  <div class="border-top pt-3">
    <small class="text-muted">
      You have been logged out <a href="{% url 'login' %}">Login Again</a>
    </small>
  </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "root/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<section class="py-5 my-5">
  <div class="container">
    <h1 class="mb-5">My Profile</h1>
    <div class="bg-white shadow rounded-lg d-block d-sm-flex">
      <div class="profile-tab-nav border-right">
        <div class="p-4">
          <div class="img-circle text-center mb-3">
            <img src="{{ user.profile.image.url }}" alt="Image" class="shadow" />
          </div>
          <h4 class="text-center">{{ user.username }}</h4>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="id_image" class="btn btn-outline-info">
                      Choose Profile
                      <input type="file" name="image" accept="image/*" style="display: none;" id="id_image">
                    </label>
                  </div>
                </div>
              </div>
            </fieldset>
            <div class="form-group">
              <p></p>
              <button class="btn btn-primary" type="submit">Update</button>
            </div>
          </form>
        </div>
      </div>
      <div class="tab-content p-4 p-md-5" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="account" role="tabpanel" aria-labelledby="account-tab">
          <h3 class="mb-4">Account Info</h3>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Edit Changes</legend>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="id_username">Username</label>
                    <input type="text" name="username" value="{{ user.username }}" maxlength="150" class="form-control custom-width ">
                  </div>
                  <div class="form-group">
                    <label for="id_email">Email</label>
                    <input type="email" name="email" value="{{ user.email }}" class="form-control custom-width ">
                  </div>
                </div>
              </div>
            </fieldset>
            <div class="form-group">
              <p></p>
              <button class="btn btn-primary" type="submit">Update</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

users/templates/users/register.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'root/main.css' %}">

    {% if title %}
        <title>FiShare - {{ title }}</title>
    {% else %}
        <title>FiShare</title>
    {% endif %}
</head>
<body class="bg">
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid" >
          <a class="navbar-brand" href="#">
            <img src="{% static 'root/logo.png' %}" alt="Bootstrap" width="30" height="30" >
            FiShare
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            	{% if user.is_authenticated %}
            	 <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
            	 <a class="nav-item nav-link" href="#">Profile</a>
            	{%else%} 
	              <a class="nav-item nav-link" href="{% url 'login'%}">Login</a>
	            {%endif%}  
            </div>
          </div>
        </div>
      </nav>
    </div>
    </header>


    <main role="main" class="container">
      <div class="row">
        <div class="col">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          <div class="center-screen">
            <div class="content-section" >
            <form method="POST">
                  {% csrf_token %}
                  <fieldset class="form-group">
                      <legend class="border-bottom mb-4">Register</legend>
                      {{ form|crispy }}
                  </fieldset>
                  <div class="form-group">
                      <button class="btn btn-outline-info" type="submit">Sign Up</button>
                  </div>
              </form>
              <div class="border-top pt-3">
                  <small class="text-muted">
                    Already have an Account? <a class="ml-2" href= "{% url 'login' %}" >Sign In</a>
                  </small>
                </div>   
            </div>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>