FiShare/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from users import views as users_view
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', users_view.register, name='register'),
    path('profile/', users_view.profile, name='profile'),
    path('', include('allusers.urls')),
    path('', include('root.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/urls.py
from django.urls import path
from .views import (PostCreateView,download_file,FileDelete,create_folder,
                    MyFileFolderView,home,download_folder,FolderDelete, 
                    toggle_favorite, FolderUpload, FolderUploadIndex)
from django.conf.urls.static import static
from django.conf import settings


urlpatterns =[
    path('',home ,name='home'),
    path('my_files/',MyFileFolderView.as_view(),name='all_files'),
    path('my_files/new/',PostCreateView.as_view(template_name='root/add_file.html'),name='all_files_create'),
    path('my_files/<int:pk>/delete/', FileDelete.as_view(), name='delete_file'),
    path('my_files/folder/create', create_folder,name='create_folder'),
    path('my_files/folder/create/<int:parent_folder_id>/',PostCreateView.as_view(template_name='root/add_file.html'),name='create_file_in_folder'),
    path('my_files/folder/create/folder/<int:parent_folder_id>/',create_folder,name='create_folder_in_folder'),
    path('my_files/<int:parent_folder_id>/',MyFileFolderView.as_view(template_name='root/subfolder.html'),name='subfolder'),
    path('download/file/<str:file_path>/', download_file, name='download_file'),
    path('download/folder/<int:pk>/', download_folder, name='download_folder'),
    path('delete/folder/<int:pk>/', FolderDelete.as_view(), name='delete_folder'),
    path('toggle_favorite/<str:model>/<int:pk>/', toggle_favorite , name='toggle_favorite'),
    path('folder_upload/<int:pk>/', FolderUpload, name='folder_upload'),
    path('folder_upload_index/', FolderUploadIndex, name='folder-upload-index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
import os

# from django.db.models.signals import pre_delete
# from django.dispatch import receiver
# import os

# def delete_file(instance, **kwargs):
#     if instance.file:
#         if os.path.isfile(instance.file.path):
#             os.remove(instance.file.path)

# @receiver(pre_delete, sender=User)
# def delete_files(sender, instance, **kwargs):
#     for blog_post in instance.blogpost_set.all():
#         delete_file(blog_post)

class Folder(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    parent_folder = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    is_favorite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name
    

class AllFiles(models.Model):
    owner= models.ForeignKey(User, on_delete=models.CASCADE)
    title= models.CharField(max_length=100)
    file=models.FileField(upload_to='all_files/', default='')
    created_at=models.DateTimeField(auto_now_add=True,)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE, null=True, blank=True)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk':self.pk})
    
    def delete(self, *args, **kwargs):
        if self.file:
            os.remove(self.file.path)
        super().delete(*args, **kwargs)

    def filename(self):
        return os.path.basename(self.file.name)

root/forms.py
from django import forms
from .models import Folder

class FolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = [ 'name' ]
        
class FolderUploadForm(forms.ModelForm):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True, 'webkitdirectory': True, 'directory': True}))

    class Meta:
        model = Folder
        fields = ['file',]

root/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (CreateView,DeleteView,TemplateView)
from .models import AllFiles,Folder
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from .forms import FolderForm, FolderUploadForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import FileResponse,HttpResponse,HttpResponseRedirect
import os,io
import zipfile
from django.utils.text import slugify



@login_required
def create_folder(request, parent_folder_id=None):
    parent_folder=None
    if parent_folder_id:
        parent_folder = Folder.objects.get(id=parent_folder_id)
    if request.method == 'POST':
        form = FolderForm(request.POST)
        if form.is_valid():
            folder = form.save(commit=False)
            folder.user = request.user  # Set the user for the folder
            folder.parent_folder = parent_folder 
            folder.save()
            if parent_folder:
                return redirect('subfolder',parent_folder_id=parent_folder_id)
            else:
                return redirect('all_files')

    else:
        form = FolderForm()
    return render(request, 'root/create_folder.html', {'folderform': form})


@login_required
def home(request):
    logged_user=request.user
    favorite_files = AllFiles.objects.filter(is_favorite=True,folder=None,owner=logged_user)
    favorite_folders = Folder.objects.filter(is_favorite=True, parent_folder=None,user=logged_user)
    context = {
        'files': favorite_files,
        'folders': favorite_folders,
    }
    return render(request, 'root/all_files.html',context )



def download_file(request, file_path):
    # Assuming file_path is the path to the file you want to download
    file_name=os.path.basename(file_path)
    file = open(file_path, 'rb')
    response = FileResponse(file)
    response['Content-Disposition'] = 'attachment; filename="{}"'.format(file_name)  # Set the desired filename
    return response



def download_folder(request,pk):
    folder = get_object_or_404(Folder, pk=pk)
    folder_name = folder.name
    zip_subdir = folder_name
    zip_filename = zip_subdir + ".zip"
    byte_stream = io.BytesIO()
    zf = zipfile.ZipFile(byte_stream, "w")

    folder_list = Folder.objects.filter(parent_folder=folder)
    file_list = AllFiles.objects.filter(folder=folder)

    zf = zip_them_all(file_list,folder_list,zip_subdir,zf)

    zf.close()
    response = HttpResponse(byte_stream.getvalue(), content_type="application/x-zip-compressed")
    response['Content-Disposition'] = 'attachment; filename=%s' % zip_filename
    return response


def FolderUpload(request,pk):
    if request.method == 'POST':
        form = FolderUploadForm(request.POST, request.FILES)

        p = request.POST['path']

        print(p)
        print(p,1)
        file_path_list = []
        t = ""
        for i in range(len(p)):
            if p[i]!=",":
                t = t+p[i]
            else:
                file_path_list.append(t)
                t = ""

        pathlist_list = []

        for path in file_path_list:
            t = ""
            list = []
            for i in range(len(path)):
                if path[i]!='/':
                    t = t + path[i]
                else:
                    list.append(t)
                    t = ""
            pathlist_list.append(list)

        for path in pathlist_list:
            for i in range(len(path)):
                if i==0:
                    try:
                        link = Folder.objects.get(pk=pk)
                        fol = Folder.objects.get(parent_folder=link,name=path[i])
                    except Folder.DoesNotExist:
                        new_folder = Folder(name=path[i],parent_folder=link,user=request.user)
                        new_folder.save()
                        path[i] = new_folder
                    else:
                        path[i] = fol
                else:
                    try:
                        fol = Folder.objects.get(parent_folder=path[i-1],name=path[i])
                    except Folder.DoesNotExist:
                        new_folder = Folder(name=path[i],parent_folder=path[i-1],user=request.user)
                        new_folder.save()
                        path[i] = new_folder
                    else:
                        path[i] = fol


        if form.is_valid():
            index = 0
            for field in request.FILES.keys():
                for formfile in request.FILES.getlist(field):
                    pa = pathlist_list[index]


                    folder = pa[len(pa)-1]

                    f = AllFiles(file=formfile,owner=request.user,folder=folder )
                    f.name = f.filename()
                    f.save()
                    index = index+1

        return redirect('subfolder',pk)
    else:
        form = FolderUploadForm(None)
        return render(request,'root/folder_upload.html',{'form':form})


def zip_them_all(file_list,folder_list,zip_path,zf):
    for p in file_list:
        item = p
        file_name, file_extension = os.path.splitext(item.file.file.name)
        file_extension = file_extension[1:]
        x = -1*len(file_extension)
        response = HttpResponse(item.file.file,
            content_type = "file/%s" % file_extension)
        response["Content-Disposition"] = "attachment;"\
            "filename=%s.%s" %(slugify(item.title)[:x], file_extension)

        filename = slugify(item.title)[:x]
        filename = filename + "." + file_extension
        f1 = open(filename , 'wb')
        f1.write(response.content)
        f1.close()

        pa = os.path.join(zip_path,filename)
        zf.write(filename,pa, zipfile.ZIP_DEFLATED)


    for p in file_list:
        item = p
        file_name, file_extension = os.path.splitext(item.file.file.name)
        file_extension = file_extension[1:]
        x = -1*len(file_extension)
        filename = slugify(item.title)[:x]
        filename = filename + "." + file_extension

        location = os.path.abspath(filename)
        os.remove(location)


    for p in folder_list:
        dir = p.name
        z_path = os.path.join(zip_path, dir)
        fo_list = Folder.objects.filter(parent_folder=p)
        fi_list = AllFiles.objects.filter(folder=p)
        zf = zip_them_all(fi_list,fo_list,z_path,zf)


    return zf

def FolderUploadIndex(request):
    if request.method == 'POST':
        form = FolderUploadForm(request.POST, request.FILES)
        p = request.POST.get('path', '')
        file_path_list = []
        t = ""
        for i in range(len(p)):
            if p[i]!=",":
                t = t+p[i]
            else:
                file_path_list.append(t)
                t = ""

        pathlist_list = []

        for path in file_path_list:
            t = ""
            list = []
            for i in range(len(path)):
                if path[i]!='/':
                    t = t + path[i]
                else:
                    list.append(t)
                    t = ""
            pathlist_list.append(list)

        for path in pathlist_list:
            for i in range(len(path)):
                if i==0:
                    try:
                        fol = Folder.objects.get(parent_folder=None,name=path[i],user=request.user)
                    except Folder.DoesNotExist:
                        new_folder = Folder(name=path[i],user=request.user)
                        new_folder.save()
                        path[i] = new_folder
                    else:
                        path[i] = fol
                else:
                    try:
                        fol = Folder.objects.get(parent_folder=path[i-1],name=path[i])
                    except Folder.DoesNotExist:
                        new_folder = Folder(name=path[i],parent_folder=path[i-1],user=request.user)
                        new_folder.save()
                        path[i] = new_folder
                    else:
                        path[i] = fol


        if form.is_valid():
            index = 0
            for field in request.FILES.keys():
                for formfile in request.FILES.getlist(field):
                    pa = pathlist_list[index]
                    folder = pa[len(pa)-1]
                    f = AllFiles(file=formfile,owner=request.user,folder=folder )
                    f.name = f.filename()
                    f.save()
                    index = index+1

        return redirect('all_files')
    else:
        form = FolderUploadForm(None)
        return render(request,'root/folder_upload.html',{'form':form})



def toggle_favorite(request, model, pk):
        
        if model == 'File':
            item = get_object_or_404(AllFiles, pk=pk)
        elif model == 'Folder':
            item = get_object_or_404(Folder, pk=pk)
        else:
            return reverse('home')
        
        item.is_favorite = not item.is_favorite
        item.save()

        if item.is_favorite:
            messages.success(request, 'Added to favorites')
        else:
            messages.success(request, 'Removed from favorites')

        # Redirect back to the referring page
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # Redirect back to the referring page
    # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class MyFileFolderView(TemplateView):
    template_name = 'root/all_files.html'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        folder_id=None
        folder_id = self.kwargs.get('parent_folder_id')
        folderuser=None
        logged_user=None
        logged_user=self.kwargs.get('user_id')

        if logged_user:
            logged_user=self.kwargs.get('user_id')

        elif folder_id:
            folderuser=Folder.objects.get(id=folder_id)

root/templates/root/add_file.html
{% extends "root/base.html" %} {% load crispy_forms_tags %} {% block content %}
<div class="content-section">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Upload file</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Submit</button>
    </div>
  </form>
</div>
{% endblock content %}

root/templates/root/all_files.html
{% extends "root/home_base.html" %}
{% load static %}

{% block favourite %}
<!-- <div class="dropdown action-buttons" >
  <button class="btn btn-primary dropdown-toggle" type="button" id="actionDropdownButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Actions
  </button>
  <div class="dropdown-menu" aria-labelledby="actionDropdownButton">
    <a href="{% url 'create_folder' %}" class="dropdown-item" style="background-color: #00a2ff;">Create Folder</a>
    <a href="{% url 'all_files_create' %}" class="dropdown-item">Upload File</a>
    <a href="{% url 'folder-upload-index' %}" class="dropdown-item">Upload Folder</a>
  </div>
</div> -->

<div style="position: fixed; top: 20px; right: 20px;">
<details class="dropdown action-buttons" style=" 
  --button-background: rgb(65, 160, 255);
  --button-color: white;
  
  --dropdown-highlight: dodgerblue;
  --dropdown-width: 160px;
  --dropdown-background: rgb(0, 208, 255);
  --dropdown-color: rgb(255, 255, 255);



  display: flex;
  justify-content: center;
  align-items: center;
  /* min-height: 100vh; */
  background-color: #ffffff;
">
  <summary role="button">
    <a class="button" style="text-decoration: none;">Edit</a>
  </summary>
  <ul>
    <li><a href="{% url 'create_folder' %}">Create Folder</a></li>
    <li><a href="{% url 'all_files_create' %}">Upload File</a></li>
    <li><a href="{% url 'folder-upload-index' %}">Upload Folder</a></li>
</ul>
</details>
</div>

{% endblock favourite %} 

{% block homescript %}
<script>
  $(document).ready(function () {
    $(".favorite-button").click(function () {
      $(this).toggleClass("clicked");
    });
  });
</script>
{% endblock homescript %}

root/templates/root/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if title %}
    <title>FiShare- {{ title }}</title>
    {% else %}
    <title>FiShare</title>
    {% endif %}
    <!-- bootstrap 5 css -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
      integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
    <!-- custom css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'root/home.css' %}"
    />
  
  </head>

  <body>
    <nav
      class="navbar navbar-expand d-flex flex-column align-item-start active-nav"
      id="sidebar"
    >
      <a href="#" class="navbar-brand text-light mt-5">
        <div class="display-5 font-weight-bold">FiShare</div>
      </a>
      <ul class="navbar-nav d-flex flex-column mt-5 w-100">
        <li class="nav-item w-100">
          <a href="{% url 'home'%}" class="nav-link text-light pl-4">Home</a>
        </li>
        <li class="nav-item w-100">
          <a href="{% url 'all_files'%}" class="nav-link text-light pl-4"
            >My Files</a
          >
        </li>
        <li class="nav-item w-100">
          <a href="{% url 'all_users'%}" class="nav-link text-light pl-4"
            >Users</a
          >
        </li>
        <li class="nav-item w-100">
          <a href="{% url 'profile'%}" class="nav-link text-light pl-4"
            >Profile</a
          >
        </li>
        <li class="nav-item w-100">
          <a href="{% url 'logout'%}" class="nav-link text-light pl-4"
            >Logout</a
          >
        </li>
        <!-- <li class="nav-item dropdown w-100">
                <a href="#" class="nav-link dropdown-toggle text-light pl-4" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">Service</a>
                <ul class="dropdown-menu w-100" aria-labelledby="navbarDropdown">
                    <li><a href="#" class="dropdown-item text-light pl-4 p-2">Service 01</a></li>
                    <li><a href="#" class="dropdown-item text-light pl-4 p-2">Service 02</a></li>
                    <li><a href="#" class="dropdown-item text-light pl-4 p-2">Service 03</a></li>
                </ul>
            </li> -->
      </ul>
    </nav>
    <section class="p-4 my-container active-cont">
      <button class="btn my-4" id="menu-btn">Toggle Sidebar</button>
      {% if messages %} {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %} {% endif %} {% block content %}{% endblock %}
    </section>

    <!-- bootstrap js -->
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    
    <script src="https://kit.fontawesome.com/f2acf4a52a.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.min.js"
      integrity="sha384-5h4UG+6GOuV9qXh6HqOLwZMY4mnLPraeTrjT5v07o347pj6IkfuoASuGBhfDsp3d"
      crossorigin="anonymous"
    ></script>
    <!-- custom js -->
    <script>
      var menu_btn = document.querySelector("#menu-btn");
      var sidebar = document.querySelector("#sidebar");
      var container = document.querySelector(".my-container");
      menu_btn.addEventListener("click", () => {
        sidebar.classList.toggle("active-nav");
        container.classList.toggle("active-cont");
      });
    </script>

    {% block script %}
    
    {% endblock script %}
  </body>
</html>

root/templates/root/create_folder.html
{% extends "root/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="formcontainer">
  <div class="card">
    <div class="card-header">
      <h2 class="card-title">Create Folder</h2>
    </div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {{ folderform.as_p }}

        <div class="text-center">
          <button class="btn btn-primary" type="submit">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

root/templates/root/folder_upload.html
{% extends "root/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="formcontainer">
  <div class="card">
    <div class="card-header">
      <h2 class="card-title">Upload Folder</h2>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div style="display:none">
          <input type="text" id="path" name="path">
        </div>
        <p><label for="id_file">File:   </label>
        <input id="id_file" type="file" name="file" multiple webkitdirectory="" onchange="myFunction()" required /></p>
        <button type="submit" class="btn btn-success">Submit</button>
    
      </form>
    </div>
  </div>
</div>

{% endblock content %}

{%block script%}

<script>
  function myFunction(){
    var x = document.getElementById("path");
    var y = document.getElementById("id_file");
    var txt = "";
    if ('files' in y) {
      for (var i = 0; i < y.files.length; i++) {
        var file = y.files[i];
        if ('webkitRelativePath' in file) {
          txt = txt + file.webkitRelativePath + ",";
        }
      }
    }
    x.value = txt
  }
</script>

{%endblock script%}

root/templates/root/home_base.html
{% extends "root/base.html" %}
{% load crispy_forms_tags %}
{% load custom_filters %}

{% block content %}







<!-- Files Section -->
<h2 class="section-title">
    <i class="fa-solid fa-file" style="font-size: 30px; margin-right: 7px;"></i>
    <span style="font-size: 30px;">Files</span></h2>
<hr class="section-line">
<div class="file-section">
  {% for post in files %}
  <article class="media content-section">
    <img class="rounded-circle article-img" 
    src="{{ post.author.profile.image.url }}" />
    <div class="media-body">

        <a class="article-title" href="{% url 'subfolder' post.id %}"
         style="text-decoration: none; color: #333; display: flex; flex-direction: column; align-items: center;">
         <i class="fa-solid fa-file fa-10x" style="color: #60b5e7;"></i>
            <h4 style="margin-top: 5px;">{{ post.title }}</h4>
          </a>

          <div class="button-row">
            <form action="{% url 'delete_file' post.pk %}" method="POST" class=" square button" style="padding: 0%;">
              {% csrf_token %}
              {% if request.user == post.owner %}
                <button type="submit" class="btn btn-danger square button" style="height: 40px">
                  <i class="fa-solid fa-trash"></i>
                </button>
              {% endif %}
            </form>
          
            <a href="{% url 'download_file' post.file.path %}" class="btn btn-primary square-button" style="background-color: #01ae0d;">
              <i class="fa-solid fa-download"></i>
            </a>
          
            {% with favorite_class=post.is_favorite|yesno:"favpurple,favblue" %}
            <a href="{% url 'toggle_favorite' 'File' post.id %}" class="btn btn-primary favorite-button square-button {{favorite_class}}">
              <i class="fa-regular fa-star"></i>
            </a>
        {% endwith %}
          </div>
          
      <div class="article-metadata">
        <small class="text-muted">
            {{ post.created_at|date:"H:i d/m/Y" }}
        </small>
      </div>
    </div>
  </article>
  {% endfor %}
</div>



<!-- Folders Section -->
<h2 class="section-title">
    <i class='fa fa-folder blue-color' 
    style="margin-right: 9px; font-size: 30px;"></i>
    <span style="font-size: 30px;">Folders</span></h2>
<hr class="section-line">
<div class="folder-section">
  {% for post in folders %}
  <article class="media content-section">
    <div class="media-body">
        
    
        <a class="article-title" href="{% url 'subfolder' post.id %}" style="text-decoration: none; color: #333; display: flex; flex-direction: column; align-items: center;">
            <i class="fas fa-folder fa-10x" style="color: #ffc800;"></i>
            <h4 style="margin-top: 5px;">{{ post.name }}</h4>
          </a>
          

          <div class="button-row">
            <form action="{% url 'delete_folder' post.pk %}" method="POST" class=" square button" style="padding: 0%; margin: 0px 0px;">
              {% csrf_token %}
              {% if request.user == post.user %}
                <button type="submit" class="btn btn-danger square button " style="height: 40px">
                  <i class="fa-solid fa-trash"></i>
                </button>
              {% endif %}
            </form>
          
            <a href="{% url 'download_folder' post.id %}" class="btn btn-primary square-button " style=" background-color: #01ae0d;
            border: none;">
              <i class="fa-solid fa-download"></i>
            </a>
          
            {% with favorite_class=post.is_favorite|yesno:"favpurple,favblue" %}
            <a href="{% url 'toggle_favorite' 'Folder' post.id %}" class="btn btn-primary favorite-button square-button {{favorite_class}}">
              <i class="fa-regular fa-star"></i>
            </a>
        {% endwith %}
          </div>
          
    </div>
  </article>
  {% endfor %}
</div>

{% block favourite %}
{% endblock favourite %}

{% endblock content %}

{% block script %}
{% block homescript %}

{% endblock homescript %}
{% endblock script %}

root/templates/root/subfolder.html
{% extends "root/home_base.html" %} {%block favourite%} 
{% if folderuser == request.user %}
<div style="position: fixed; top: 20px; right: 20px">
  <details
    class="dropdown action-buttons"
    style="
      --button-background: rgb(65, 160, 255);
      --button-color: white;

      --dropdown-highlight: dodgerblue;
      --dropdown-width: 160px;
      --dropdown-background: rgb(0, 208, 255);
      --dropdown-color: rgb(255, 255, 255);

      display: flex;
      justify-content: center;
      align-items: center;
      /* min-height: 100vh; */
      background-color: #ffffff;
    "
  >
    <summary role="button">
      <a class="button" style="text-decoration: none">Edit</a>
    </summary>
    <ul>
      <li><a href="{% url 'create_folder' %}">Create Folder</a></li>
      <li><a href="{% url 'create_file_in_folder' parent_folder_id %}">Upload File</a></li>
      <li>
        <a href="{% url 'folder_upload' parent_folder_id %}">Upload Folder</a>
      </li>
    </ul>
  </details>
</div>
{% endif %} {%endblock favourite%}